version: 2
# registries:
#   npm-registry-npm-pkg-github-com:
#     type: npm-registry
#     url: https://npm.pkg.github.com
#     token: '${{secrets.DEPENDABOT_TOKEN}}'
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '08:00'
    target-branch: master
#     registries:
#       - npm-registry-npm-pkg-github-com
